### ISSUE TITLE
Issue with new gemmi version 0.7.0

### ISSUE THREAD

**Issue by jdickerson95** [teamtomo/mmdf#9]
I'm getting this error with the new gemmi version 0.7.0 released on 30 Nov 2024
 "AttributeError: 'gemmi.Model' object has no attribute 'name'"

Looking at the release notes: 
"replaced string Model::name with int Model::num"

I opened an issue instead of a PR because I'm unsure if it's best to specify the gemmi version in the dependencies or update mmdf.

**Comment by alisterburt** [comment]
@jdickerson95 sorry for missing this, notification settings here must be dodgy

I vote we move this package to follow the new gemmi API, specify a minimum version and cut a release

**Comment by jdickerson95** [comment]
Crated a pul request. I specified the exact version instead of minimum in case future versions change again, but easy to change this.

**Comment by alisterburt** [comment]
closed by #10 

@jdickerson95 I've given you admin here, could you or Matthew handle pushing a release?

Should be something like the following to release, typical git remote setup is `origin` for your own fork and `upstream` for `teamtomo/mmdf`, make sure your local main branch is tracking the remote main branch with `git branch --set-upstream-to=upstream/main main`

```sh
git checkout main
git pull
git tag -a v0.0.3 -m "v0.0.3"
git push --follow-tags upstream main 
```

**Comment by mgiammar** [comment]
Will do thanks!

**Comment by alisterburt** [comment]
@mgiammar the above should launch the following workflow on GitHub actions 
https://github.com/teamtomo/mmdf/blob/c448dae17425bfc30740fc35a90a4fd4bac54570/.github/workflows/ci.yml#L74-L108

You can check whether this happened in the *Actions* tab at the top of the repo

**Comment by alisterburt** [comment]
any questions/issues don't hestitate

**Comment by alisterburt** [comment]
@mgiammar looks like you got it all figured out, congrats on your first teamtomo release!!

**Comment by mgiammar** [comment]
Whoohoo! Thanks again
